name: open_folder
description: "A Flutter plugin to open folders on Android, iOS, macOS, Windows, and Linux platforms."
version: 0.0.3
homepage: https://github.com/SwanFlutter/open_folder
repository: https://github.com/SwanFlutter/open_folder
issue_tracker: https://github.com/SwanFlutter/open_folder/issues

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:

  plugin:
    platforms:
      android:
        package: com.example.open_folder
        pluginClass: OpenFolderPlugin
        dartPluginClass: OpenFolder
      ios:
        pluginClass: OpenFolderPlugin
        dartPluginClass: OpenFolder
      linux:
        pluginClass: OpenFolderPlugin
        dartPluginClass: OpenFolder
      macos:
        pluginClass: OpenFolderPlugin
        dartPluginClass: OpenFolder
      windows:
        pluginClass: OpenFolderPluginCApi
        dartPluginClass: OpenFolder

 
